import xml.etree.ElementTree as ET
import urllib.request, urllib.parse, urllib.error

iIO = '''<commentinfo>
<comments>
<comment>
<name>Dewi</name>
<count>100</count>
</comment>
<comment>
<name>Sherwyn</name>
<count>98</count>
</comment>
<comment>
<name>Kahlya</name>
<count>98</count>
</comment>
<comment>
<name>Meabh</name>
<count>94</count>
</comment>
<comment>
<name>Lillia</name>
<count>92</count>
</comment>
<comment>
<name>Sohera</name>
<count>92</count>
</comment>
<comment>
<name>Olurotimi</name>
<count>91</count>
</comment>
<comment>
<name>Jena</name>
<count>91</count>
</comment>
<comment>
<name>Sheonagh</name>
<count>90</count>
</comment>
<comment>
<name>Mercedez</name>
<count>90</count>
</comment>
<comment>
<name>Sharmaine</name>
<count>88</count>
</comment>
<comment>
<name>Emilia</name>
<count>88</count>
</comment>
<comment>
<name>Darrell</name>
<count>83</count>
</comment>
<comment>
<name>Martina</name>
<count>81</count>
</comment>
<comment>
<name>Lauchlan</name>
<count>79</count>
</comment>
<comment>
<name>Shiraz</name>
<count>77</count>
</comment>
<comment>
<name>Hayleigh</name>
<count>73</count>
</comment>
<comment>
<name>Roslyn</name>
<count>72</count>
</comment>
<comment>
<name>Kelsiee</name>
<count>72</count>
</comment>
<comment>
<name>Yasmine</name>
<count>70</count>
</comment>
<comment>
<name>Ally</name>
<count>69</count>
</comment>
<comment>
<name>Cullen</name>
<count>68</count>
</comment>
<comment>
<name>Zayne</name>
<count>66</count>
</comment>
<comment>
<name>Abel</name>
<count>65</count>
</comment>
<comment>
<name>Alishan</name>
<count>63</count>
</comment>
<comment>
<name>Christabel</name>
<count>61</count>
</comment>
<comment>
<name>Kira</name>
<count>60</count>
</comment>
<comment>
<name>Aedan</name>
<count>60</count>
</comment>
<comment>
<name>Greig</name>
<count>59</count>
</comment>
<comment>
<name>Aleksandar</name>
<count>59</count>
</comment>
<comment>
<name>Darrach</name>
<count>58</count>
</comment>
<comment>
<name>Ishwari</name>
<count>57</count>
</comment>
<comment>
<name>Nur</name>
<count>54</count>
</comment>
<comment>
<name>Iagan</name>
<count>48</count>
</comment>
<comment>
<name>Krystyna</name>
<count>47</count>
</comment>
<comment>
<name>Tarik</name>
<count>45</count>
</comment>
<comment>
<name>Enrico</name>
<count>40</count>
</comment>
<comment>
<name>Logann</name>
<count>32</count>
</comment>
<comment>
<name>Jaelyn</name>
<count>32</count>
</comment>
<comment>
<name>Lucas</name>
<count>32</count>
</comment>
<comment>
<name>Deshawn</name>
<count>24</count>
</comment>
<comment>
<name>Syeda</name>
<count>22</count>
</comment>
<comment>
<name>Lagan</name>
<count>13</count>
</comment>
<comment>
<name>Breagh</name>
<count>9</count>
</comment>
<comment>
<name>Nicolas</name>
<count>9</count>
</comment>
<comment>
<name>Dionne</name>
<count>8</count>
</comment>
<comment>
<name>Kyie</name>
<count>7</count>
</comment>
<comment>
<name>Aaryn</name>
<count>5</count>
</comment>
<comment>
<name>Merissa</name>
<count>3</count>
</comment>
<comment>
<name>Karl</name>
<count>3</count>
</comment>
</comments>
</commentinfo>'''

iWebText = urllib.request.urlopen('http://py4e-data.dr-chuck.net/comments_1081152.xml')

commentinfo = ET.fromstring(iIO)
dataLength = commentinfo.findall('comments/comment')
print('User Count:', len(dataLength))
summation=0
for item in dataLength:
    print('Name:',item.find('name').text)
    print('Count:',item.find('count').text)
    j=int(item.find('count').text)
    summation = summation+j
print("The result is",summation)
