print('**********************************')
print('*                                *')
print('*          BUIC                  *')
print('*        Computing               *')
print('*       Assignment 1             *')
print('*                                *')
print('**********************************')
